"""Analysis metrics on a synthetic Cα trajectory, + a guarded smoke test on demo_out.

The synthetic tests need no OpenMM/files (fast, always run). The smoke test runs the
full `analyze()` against the demo output if it exists (generated by
examples/demo_short_run.py), otherwise it skips.
"""

from pathlib import Path

import mdtraj as md
import numpy as np
import pytest

from openmm_pipelines.analysis import (
    cluster_conformations,
    radius_of_gyration,
    rmsd_to_reference,
    rmsf_per_residue,
)

DEMO = Path(__file__).parents[1] / "examples" / "MD_demo" / "demo_out"


def _toy_traj(n_frames=6, n_res=5, drift=0.02):
    top = md.Topology()
    chain = top.add_chain()
    for _ in range(n_res):
        res = top.add_residue("ALA", chain)
        top.add_atom("CA", md.element.carbon, res)
    xyz = np.zeros((n_frames, n_res, 3), dtype=np.float32)
    for f in range(n_frames):
        for r in range(n_res):
            xyz[f, r] = [r * 0.38, 0.0, 0.0]  # ~3.8 Å spacing
        xyz[f, -1, 1] += drift * f  # last residue drifts in y
    return md.Trajectory(xyz, top)


def test_rmsf_flags_the_drifting_residue():
    traj = _toy_traj()
    resseq, rmsf = rmsf_per_residue(traj)
    assert len(resseq) == 5
    assert int(rmsf.argmax()) == 4  # last residue is the mobile one
    assert rmsf[0] == pytest.approx(0.0, abs=1e-4)


def test_rmsd_to_first_frame_is_zero_at_start():
    traj = _toy_traj()
    rmsd = rmsd_to_reference(traj, traj[0])
    assert rmsd[0] == pytest.approx(0.0, abs=1e-4)
    assert rmsd[-1] > rmsd[0]  # drift grows


def test_radius_of_gyration_shape_and_positive():
    traj = _toy_traj()
    rg = radius_of_gyration(traj)
    assert rg.shape == (traj.n_frames,)
    assert np.all(rg > 0)


def test_clustering_returns_one_label_per_frame():
    traj = _toy_traj()
    labels = cluster_conformations(traj, cutoff_ang=0.5)
    assert labels.shape == (traj.n_frames,)
    assert labels.min() >= 1


@pytest.mark.skipif(not (DEMO / "production" / "trajectory.xtc").exists(),
                    reason="demo_out not present (run examples/MD_demo/demo_short_run.py)")
def test_analyze_demo_smoke():
    from openmm_pipelines.analysis import analyze

    adir = analyze(DEMO)
    for name in ("analysis_report.json", "analysis_data.npz",
                 "rmsd.png", "rg.png", "rmsf.png", "dssp.png",
                 "processed.xtc", "processed_topology.pdb"):
        assert (adir / name).exists(), f"missing {name}"
